[package]
name = "Liquid_Unemployed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "Liquid_Unemployed"
path = "src/libs.rs"


[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
glow = "0.16.0"
